import React, { useCallback } from 'react';
import { useSnapshot } from 'valtio';
import { traceStore } from '../../store/trace-store';
import { Button } from '../ui/shadcn/button';
import { Input } from '../ui/shadcn/input';
import { Upload } from 'lucide-react';

export const TraceUploader: React.FC = () => {
    const { isLoading } = useSnapshot(traceStore);

    const handleFileChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            traceStore.loadTrace(file);
        }
    }, []);

    return (
        <div className="flex flex-col items-center justify-center p-10 border-2 border-dashed rounded-lg border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-gray-900">
            <Upload className="w-12 h-12 mb-4 text-gray-400" />
            <h3 className="text-lg font-medium mb-2">Load Trace File</h3>
            <p className="text-sm text-gray-500 mb-6 text-center max-w-md">
                Select a .trace or .txt file generated by the C++ Trace utility.
            </p>
            
            <div className="flex items-center gap-2">
                <Input 
                    type="file" 
                    accept=".trace,.txt" 
                    onChange={handleFileChange} 
                    className="hidden" 
                    id="trace-upload"
                    disabled={isLoading}
                />
                <label htmlFor="trace-upload">
                    <Button asChild disabled={isLoading}>
                        <span>
                            {isLoading ? "Loading..." : "Select File"}
                        </span>
                    </Button>
                </label>
            </div>
        </div>
    );
};

