import React from 'react';
import { useSnapshot } from 'valtio';
import { traceStore } from '../../store/trace-store';
import { TopMenu } from './2-top-menu';
import { TraceMainView } from './3-trace-main-view';

export function TraceViewerApp() {
    const { lines, error } = useSnapshot(traceStore);
    const hasFile = lines.length > 0 || !!error;

    return (
        <div className="h-full flex flex-col overflow-hidden">
            <TopMenu />

            {/* Main Content Area */}
            <div className="flex-1 flex flex-col overflow-hidden relative">
                {hasFile
                    ? <TraceMainView />
                    : (
                        /* Empty State Overlay */
                        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                            <p className="text-lg text-muted-foreground">
                                Select a .trace or .txt file generated by the C++ Trace utility.
                            </p>
                        </div>
                    )
                }
            </div>
        </div>
    );
}
