import React, { useRef } from 'react';
import { useSnapshot } from 'valtio';
import { traceStore } from '../../store/trace-store';
import { TraceLoadInput, TraceOpenMenuItem } from '../trace-viewer/1-trace-uploader';
import { TraceList } from '../trace-viewer/2-trace-list';
import { FileText, Cpu, Clock } from 'lucide-react';
import {
    Menubar,
    MenubarContent,
    MenubarItem,
    MenubarMenu,
    MenubarSeparator,
    MenubarShortcut,
    MenubarTrigger,
} from "../ui/shadcn/menubar";

export function TraceViewerApp() {
    const { lines, header, error } = useSnapshot(traceStore);
    const hasFile = lines.length > 0 || !!error;
    const fileInputRef = useRef<HTMLInputElement>(null);

    return (
        <div className="h-full flex flex-col overflow-hidden">
            <TraceLoadInput inputRef={fileInputRef} />
            
            {/* Top Menu */}
            <div className="border-b">
                <Menubar className="border-none shadow-none rounded-none px-2">
                    <MenubarMenu>
                        <MenubarTrigger>File</MenubarTrigger>
                        <MenubarContent>
                            <TraceOpenMenuItem onClick={() => fileInputRef.current?.click()} />
                            <MenubarSeparator />
                            <MenubarItem disabled>
                                Exit <MenubarShortcut>Ctrl+Q</MenubarShortcut>
                            </MenubarItem>
                        </MenubarContent>
                    </MenubarMenu>
                    <MenubarMenu>
                        <MenubarTrigger>View</MenubarTrigger>
                        <MenubarContent>
                            <MenubarItem disabled>Filter...</MenubarItem>
                        </MenubarContent>
                    </MenubarMenu>
                    <MenubarMenu>
                        <MenubarTrigger>Help</MenubarTrigger>
                        <MenubarContent>
                            <MenubarItem disabled>About</MenubarItem>
                        </MenubarContent>
                    </MenubarMenu>
                </Menubar>
            </div>

            {/* Main Content Area */}
            <div className="flex-1 flex flex-col overflow-hidden relative">
                {hasFile ? (
                    <>
                        {/* Header Bar (Metadata) */}
                        <div className="border-b p-4 flex items-center gap-6 bg-background">
                            <div className="flex items-center gap-2">
                                <FileText className="w-5 h-5 text-blue-500" />
                                <h1 className="font-semibold">{header.machineName || "Trace Viewer"}</h1>
                            </div>

                            <div className="flex items-center gap-4 text-sm text-muted-foreground">
                                {header.os && <span>{header.os}</span>}
                                {header.compiled && (
                                    <div className="flex items-center gap-1">
                                        <Clock className="w-4 h-4" />
                                        <span>{header.compiled}</span>
                                    </div>
                                )}
                                <div className="flex items-center gap-1">
                                    <Cpu className="w-4 h-4" />
                                    <span>{lines.length.toLocaleString()} lines</span>
                                </div>
                            </div>
                        </div>

                        {/* Error Banner */}
                        {error && (
                            <div className="bg-red-100 border-l-4 border-red-500 text-red-700 p-4" role="alert">
                                <p className="font-bold">Error loading trace</p>
                                <p>{error}</p>
                            </div>
                        )}

                        {/* Trace List */}
                        <div className="flex-1 overflow-hidden">
                            <TraceList />
                        </div>
                    </>
                ) : (
                    /* Empty State Overlay */
                    <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                         <p className="text-lg text-muted-foreground">
                            Select a .trace or .txt file generated by the C++ Trace utility.
                        </p>
                    </div>
                )}
            </div>
        </div>
    );
}
